### PR TITLE
Load vernacularnames

### PR DESCRIPTION
**Pull request by niconoe**

### CODE REVIEW

**Review by damianooldoni — APPROVED** [review]
Hi @niconoe . Nice stuff! 
I like you put a filter on languages. 

One question and one idea for (a little) improvement:
1. I wonder whether is there a reason to convert languages from ISO 3-letter to 2-letter codes
2. Maybe adding a taxa-limit option to run vernacular names on a subset of taxa? This could be useful for developing and it would make this step similar to previous steps? So, something like this in `config.ini.example`?
```
[vernacular_names]
# taxa-limit: number | empty for all
# taxa-limit =
taxa-limit = 100
```
@niconoe : What do you think?

Anyway, this PR is very nice and can be already approved as it is.

**Comment by niconoe** [comment]
Thanks for the review!

For the 3-to-2 language conversion, this could indeed be dropped/simplified if you prefer! I initially added that for reasons that are indeed quite arbitrary: 

- there's a comment in `create_new_tables.sql` that says we follow the two-letter standard, so I blindly followed this "contract"
- At the same time, I probably wrote this comment myself just because I am much more familiar with the two-letter codes and I wasn't aware GBIF was using the less common three-letter variant.
- I also noticed there are ambiguities in the three letter codes that *could* lead to inconsistencies (Dutch being `nld` in the Netherlands, but `dut` in Belgium - GBIF doesn't care and seems to always return `nld` whatever the species/checklists/API user.

For point two, I totally agree!

**Comment by damianooldoni** [comment]
Thanks @niconoe for fast reply! 
I like 2-letter codes as well. So, let's follow the "contract" :smile: 
Are you improving adding the taxa-limit in config or do I? If you do it, I think you can merge this PR as well. Thanks!

**Comment by niconoe** [comment]
Perfect, will do!

**Comment by niconoe** [comment]
I think it's okay now!

**Comment by damianooldoni** [comment]
great work. Nice. I merge it.

**Pull request merged**
